### PR TITLE
Fix: local dev doesn't work with Redis

### PR DESCRIPTION
**Pull request by Andrew-Dickinson**
Unit tests don't pass locally on main lol

Celery tries to connect to `redis://localhost:6379/0` but that port isn't forwarded to the system from the container

### CODE REVIEW

**Comment by Andrew-Dickinson** [comment]
@james-otten you said I need to change something else when we modify this file?

**Comment by james-otten** [comment]
> @james-otten you said I need to change something else when we modify this file?

Can we not merge this until after grand goes away.
I'm this case no chance needed.

**Comment by Andrew-Dickinson** [comment]
Sure no worries

**Comment by james-otten** [comment]
Already happened xD

**Comment by Andrew-Dickinson** [comment]
Whoops :(

**Pull request closed without merging**
