### PR TITLE
Add test to expose failures in Install Integrations

### PR DESCRIPTION
**Pull request by Andrew-Dickinson**

### CODE REVIEW

**Comment by WillNilges** [comment]
What does "Install Integrations" mean?

**Comment by WillNilges** [comment]
Is there a specific failure you're trying to expose, or is this just for coverage?

**Review by WillNilges — APPROVED** [review]
More tests are always good. See above comment.

**Comment by Andrew-Dickinson** [comment]
> Is there a specific failure you're trying to expose, or is this just for coverage?

This is a regression test to expose the issue fixed by #734. That was causing a crash on the integrations because zip was the wrong type, and it slipped through our testing because the integrations were always disabled

**Pull request merged**
