### PR TITLE
Linting fixes

### PR DESCRIPTION
**Pull request by james-otten**
Various fixes for tool reported style issues.

1. Resolve all import ordering issues via `isort`
2. Resolve all style issues via `black`
3. Enable `isort . --check` in `invoke lint`
4. Enable `isort .` in `invoke format`
5. Resolve _some_ style issues identified by `flake8` (mostly unused imports)

### CODE REVIEW

**Comment by Andrew-Dickinson** [comment]
Nice, this resolves much of #266!

**Review by Andrew-Dickinson — APPROVED** [review]
Looks great, thanks for doing this!

**Review by WillNilges — APPROVED** [review]
Sweet. We oughta add some more linting tools to our pipelines.

**Comment by Andrew-Dickinson** [comment]
Note: this PR does add these tools to our pipelines, since they use pyinvoke and this PR updates the pyinvoke tasks

**Pull request merged**
