### PR TITLE
Add devices names to link.__str__ for "self links"

### PR DESCRIPTION
**Pull request by Andrew-Dickinson**
This may be a bit controversial since it makes things a bit bulky at times, but looking at the string representations for "self links" in slack is very confusing.

`NN7489 -> NN7489` is so much more confusing than `nycmesh-7489-epr7 -> nycmesh-7489-north`

For now, we only include the device names for self-links (links between devices within a single node)

This heterogenous format does look a bit messy at times, but results in a lot more clarity for single links in isolation

Screenshot 2024-11-09 at 18 48 45

Also switches to a double headed arrow to indicate that links are not directional

### CODE REVIEW

**Comment by WillNilges** [comment]
I would be OK with changing it to the device name everywhere, since all devices ought to have the NN in the name anyway.

**Review by WillNilges — APPROVED** [review]
See my above comment

**Comment by Andrew-Dickinson** [comment]
You're sure that isn't too verbose? They're so long....

**Comment by Andrew-Dickinson** [comment]
Let's keep it this way for now, and if we decide we don't like the inconsistency later we can tweak it

**Pull request merged**
