### PR TITLE
Cleanup env vars

### LINKED ISSUE #535: Cleanup env vars from helm
https://github.com/nycmeshnet/meshdb/pull/508 removes some env vars, clean them up after it is merged

### PR DESCRIPTION
**Pull request by james-otten**
Resolves #535

Cleanup unused vars.

**After merging this, remove them from the environments**

### CODE REVIEW

**Comment by Andrew-Dickinson** [comment]
How are backups configured?

**Comment by james-otten** [comment]
> How are backups configured?

https://github.com/nycmeshnet/meshdb/blob/main/src/meshdb/settings.py#L287
https://github.com/nycmeshnet/meshdb/blob/main/src/meshapi/tasks.py#L24

**Comment by Andrew-Dickinson** [comment]
We might want to bring these back as part of the fix for #694 right?

**Comment by WillNilges** [comment]
Yeah we should look at those and make sure this won't break anything.

**Review by WillNilges — APPROVED** [review]

**Comment by james-otten** [comment]
I think these will come back :'(

**Pull request closed without merging**
