### PR TITLE
Add link to PG admin to homepage

### PR DESCRIPTION
**Pull request by Andrew-Dickinson**

### CODE REVIEW

**Review by james-otten — APPROVED** [review]
I approve, but probably don't merge until the cert is fixed

**Comment by james-otten** [comment]
This URL is going to change, so, careful

**Review by WillNilges — CHANGES_REQUESTED** [review]
"Django literally has features for that"
- Andrew, 2024

We should hold off until the dust is settled here.

**Comment by Andrew-Dickinson** [comment]
Okay so with Jame's change, this PR is ready to go, I think? @WillNilges

**Review by WillNilges — APPROVED** [review]

**Pull request merged**
