### PR TITLE
Fixed bin number input issue

### PR DESCRIPTION
**Pull request by owais34**
Fixes issue : https://github.com/nycmeshnet/meshdb/issues/309

### CODE REVIEW

**Review by WillNilges — CHANGES_REQUESTED** [review]
I think there's a slightly easier way to do this with a widget override in `BuildingAdminForm`

```
"bin" : forms.NumberInput(attrs={
    "style": "width:25ch"
})
```

**Comment by owais34** [comment]
Great suggestion ,  i'll make this update .

**Review by WillNilges — APPROVED** [review]
Thanks for the contribution. Will merge once Black is appeased :)

**Comment by Andrew-Dickinson** [comment]
FYI @owais34 you can fix all formatting issues easily by running `invoke format` in the root of the project

**Pull request merged**
